id = "dep-lens"
name = "Dep Lens"
version = "0.1.2"
schema_version = 1
authors = ["gaoxiao"]
description = "Dep Lens shows dependency health signals directly in your editor so you can quickly evaluate third-party packages while coding."
repository = "https://github.com/gaoxiao6331/dep-lens"

[language_servers.dep-lens]
name = "Dep Lens"
languages = ["Go", "Go Mod"]
